Import TryFrom to unbreak generate
This was changed from 2021 edition to 2018 edition in 214511dde3b47be5c2346a240ddeaceb0481cf28,
which no longer has TryFrom in prelude.

    error[E0599]: no function or associated item named `try_from` found for type `u8` in the current scope
      --> generate/src/main.rs:56:27
       |
    56 |             let new = u8::try_from(chunkmap.len()).unwrap();
       |                           ^^^^^^^^ function or associated item not found in `u8`
       |
       = help: items from traits can only be used if the trait is in scope
    help: the following trait is implemented but not in scope; perhaps add a `use` for it:
       |
    11 | use std::convert::TryFrom;
       |

    error[E0599]: no function or associated item named `try_from` found for type `u8` in the current scope
       --> generate/src/main.rs:119:17
        |
    119 |             u8::try_from(halfdense.len() / (CHUNK / 2)).unwrap(),
        |                 ^^^^^^^^ function or associated item not found in `u8`
        |
        = help: items from traits can only be used if the trait is in scope
    help: the following trait is implemented but not in scope; perhaps add a `use` for it:
        |
    11  | use std::convert::TryFrom;
        |

    error[E0599]: no function or associated item named `try_from` found for type `u8` in the current scope
       --> generate/src/main.rs:136:21
        |
    136 |                 u8::try_from(halfdense.len() / (CHUNK / 2) - 1).unwrap(),
        |                     ^^^^^^^^ function or associated item not found in `u8`
        |
        = help: items from traits can only be used if the trait is in scope
    help: the following trait is implemented but not in scope; perhaps add a `use` for it:
        |
    11  | use std::convert::TryFrom;
        |